// Command frameworkgen regenerates the framework files that are derived from
// released dependencies and the content manifests used by safe upgrades.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hollis-labs/nanite/internal/fsutil"
)

const (
	tesseractModule = "github.com/hollis-labs/tesseract"
	tesseractGuide  = "docs/guides/tesseract-adoption-and-v0.9-migration.md"
)

type moduleInfo struct {
	Path    string
	Version string
	Dir     string
}

type manifest struct {
	SchemaVersion    int               `json:"schema_version"`
	FrameworkVersion string            `json:"framework_version"`
	Source           string            `json:"source,omitempty"`
	Files            map[string]string `json:"files"`
	RetiredPaths     []string          `json:"retired_paths,omitempty"`
	LegacyAllowPaths []string          `json:"legacy_allow_paths,omitempty"`
}

func main() {
	var (
		sourcePath     = flag.String("source", "framework", "framework source directory")
		manifestPath   = flag.String("manifest", "manifests/current.json", "current manifest output")
		tesseractDoc   = flag.String("tesseract-doc", "framework/docs/tesseract-v0.9-contract.md", "generated Tesseract guide output")
		retiredCSV     = flag.String("retired", "", "comma-separated paths retired by the current framework")
		legacyAllowCSV = flag.String("legacy-allow", "", "comma-separated history/migration files allowed to name retired contracts")
		legacyRef      = flag.String("legacy-ref", "", "optional git revision used to generate a historical manifest")
		legacyManifest = flag.String("legacy-manifest", "", "historical manifest output (required with -legacy-ref)")
		checkOnly      = flag.Bool("check", false, "fail instead of updating stale outputs")
	)
	flag.Parse()

	if (*legacyRef == "") != (*legacyManifest == "") {
		fatal(errors.New("-legacy-ref and -legacy-manifest must be supplied together"))
	}

	info, err := resolveModule(tesseractModule)
	if err != nil {
		fatal(err)
	}
	if info.Version == "" || info.Dir == "" {
		fatal(fmt.Errorf("%s is not pinned to a released module directory", tesseractModule))
	}
	guide, err := os.ReadFile(filepath.Join(info.Dir, tesseractGuide))
	if err != nil {
		fatal(fmt.Errorf("read %s@%s %s: %w", info.Path, info.Version, tesseractGuide, err))
	}
	generatedGuide := append([]byte(fmt.Sprintf(
		"<!-- Code generated by go generate ./internal/assets; DO NOT EDIT. -->\n<!-- Source: %s@%s/%s -->\n\n",
		info.Path, info.Version, tesseractGuide)), guide...)
	if emitErr := emit(*tesseractDoc, generatedGuide, *checkOnly); emitErr != nil {
		fatal(emitErr)
	}

	retired := splitAndSort(*retiredCSV)
	legacyAllow := splitAndSort(*legacyAllowCSV)
	current, err := manifestFromDir(*sourcePath, info.Path+"@"+info.Version, retired, legacyAllow)
	if err != nil {
		fatal(err)
	}
	encoded, err := encodeManifest(current)
	if err != nil {
		fatal(err)
	}
	if emitErr := emit(*manifestPath, encoded, *checkOnly); emitErr != nil {
		fatal(emitErr)
	}

	if *legacyRef != "" {
		legacy, err := manifestFromGit(*legacyRef, *sourcePath)
		if err != nil {
			fatal(err)
		}
		encodedLegacy, err := encodeManifest(legacy)
		if err != nil {
			fatal(err)
		}
		if emitErr := emit(*legacyManifest, encodedLegacy, *checkOnly); emitErr != nil {
			fatal(emitErr)
		}
	}
}

func resolveModule(path string) (moduleInfo, error) {
	// #nosec G204 -- the executable is fixed and path is the package constant above.
	cmd := exec.Command("go", "list", "-m", "-json", path)
	output, err := cmd.Output()
	if err != nil {
		return moduleInfo{}, fmt.Errorf("resolve module %s: %w", path, err)
	}
	var info moduleInfo
	if err := json.Unmarshal(output, &info); err != nil {
		return moduleInfo{}, fmt.Errorf("decode module %s: %w", path, err)
	}
	if info.Path != path {
		return moduleInfo{}, fmt.Errorf("resolved module path %q, want %q", info.Path, path)
	}
	return info, nil
}

func manifestFromDir(root, source string, retired, legacyAllow []string) (manifest, error) {
	// #nosec G304 -- root is an explicit generator input inside the repository.
	versionBytes, err := os.ReadFile(filepath.Join(root, "VERSION"))
	if err != nil {
		return manifest{}, fmt.Errorf("read framework VERSION: %w", err)
	}
	m := manifest{
		SchemaVersion:    1,
		FrameworkVersion: strings.TrimSpace(string(versionBytes)),
		Source:           source,
		Files:            make(map[string]string),
		RetiredPaths:     retired,
		LegacyAllowPaths: legacyAllow,
	}
	err = filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		// #nosec G304 G122 -- filepath.WalkDir supplied a path under the explicit repository source root.
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		m.Files[filepath.ToSlash(rel)] = digest(data)
		return nil
	})
	if err != nil {
		return manifest{}, fmt.Errorf("scan framework source: %w", err)
	}
	return m, nil
}

func manifestFromGit(ref, workingSource string) (manifest, error) {
	repoRoot, err := gitOutput("rev-parse", "--show-toplevel")
	if err != nil {
		return manifest{}, err
	}
	absSource, err := filepath.Abs(workingSource)
	if err != nil {
		return manifest{}, err
	}
	relSource, err := filepath.Rel(strings.TrimSpace(repoRoot), absSource)
	if err != nil {
		return manifest{}, err
	}
	relSource = filepath.ToSlash(relSource)
	pathsRaw, err := gitOutput("ls-tree", "-r", "--name-only", ref, "--", relSource)
	if err != nil {
		return manifest{}, err
	}
	m := manifest{SchemaVersion: 1, Source: "git:" + ref, Files: make(map[string]string)}
	for _, repoPath := range strings.Split(strings.TrimSpace(pathsRaw), "\n") {
		if repoPath == "" {
			continue
		}
		// #nosec G204 -- git ref and repository paths are explicit generator inputs, never runtime/user request data.
		data, err := exec.Command("git", "show", ref+":"+repoPath).Output()
		if err != nil {
			return manifest{}, fmt.Errorf("git show %s:%s: %w", ref, repoPath, err)
		}
		rel := strings.TrimPrefix(repoPath, strings.TrimSuffix(relSource, "/")+"/")
		m.Files[rel] = digest(data)
		if rel == "VERSION" {
			m.FrameworkVersion = strings.TrimSpace(string(data))
		}
	}
	if m.FrameworkVersion == "" || len(m.Files) == 0 {
		return manifest{}, fmt.Errorf("git revision %s has no complete framework tree at %s", ref, relSource)
	}
	return m, nil
}

func gitOutput(args ...string) (string, error) {
	// #nosec G204 -- this build-time generator constructs every argument from fixed operations or explicit developer flags.
	output, err := exec.Command("git", args...).Output()
	if err != nil {
		return "", fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
	}
	return string(output), nil
}

func encodeManifest(m manifest) ([]byte, error) {
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode manifest: %w", err)
	}
	return append(data, '\n'), nil
}

func emit(path string, want []byte, checkOnly bool) error {
	// #nosec G304 -- path is an explicit repository generator output.
	got, err := os.ReadFile(path)
	if err == nil && bytes.Equal(got, want) {
		return nil
	}
	if checkOnly {
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("read generated output %s: %w", path, err)
		}
		return fmt.Errorf("generated output is stale: %s (run go generate ./internal/assets)", path)
	}
	// #nosec G301 -- generated source directories must be readable by repository users.
	if mkdirErr := os.MkdirAll(filepath.Dir(path), 0o755); mkdirErr != nil {
		return fmt.Errorf("create output directory for %s: %w", path, mkdirErr)
	}
	if writeErr := fsutil.AtomicWriteFile(path, want, 0o644); writeErr != nil {
		return fmt.Errorf("write generated output %s: %w", path, writeErr)
	}
	return nil
}

func splitAndSort(value string) []string {
	if strings.TrimSpace(value) == "" {
		return nil
	}
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		if trimmed := strings.TrimSpace(part); trimmed != "" {
			out = append(out, filepath.ToSlash(trimmed))
		}
	}
	sort.Strings(out)
	return out
}

func digest(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "frameworkgen:", err)
	os.Exit(1)
}
